# Generated by Django 5.0.2 on 2024-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock_threshold',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books')], max_length=100, null=True),
        ),
    ]
